### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by j-kolberg** [usnistgov/NFIQ2#1]
I can build OpenCV and **make** NFIQ2 without errors, however **sudo make install** NFIQ2 always quits with the following error:
>$ sudo make install
>make[1]: Entering directory '.../biomdi'
>make[2]: Entering directory '.../biomdi/common'
>/usr/local/man/man1 does not exist
>exit 2
>make[2]: *** [/usr/local/man/man1] Error 2
>make[2]: Leaving directory '.../biomdi/common'
>make[1]: *** [install] Error 1
>make[1]: Leaving directory '.../biomdi'
>make: *** [install] Error 1

tested on
* Manjaro 17.0.6 Kernel 4.9
* Manjaro 17.0.6 Kernel 4.13
* Ubuntu 16.04
* CentOS 7

**Comment by bmwoodgate** [comment]
Currently you have to make that directory yourself. "/usr/local/man/man1"

**Comment by j-kolberg** [comment]
Thanks, that solved the problem. Maybe you should add this comment to the readme, too.

For execution, 3 more libs are required in addition to `libbiomdi.so`:
- libfmr.so
- libopencv_core.so
- libnfiq2.so

I located them and provide the commands to set the library path: (I guess it will help others, if you include these commands in the readme as well.)
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/NFIQ2/biomdi/common/lib/
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/NFIQ2/biomdi/fingerminutia/src/libfmr/
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/NFIQ2/libOpenCV/lib/
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/NFIQ2/NFIQ2/NFIQ2Algorithm/lib/

**Comment by lfares** [comment]
I set the library path with these commands that you showed here and run ldconfig after but I am still getting this error:
./NFIQ2: error while loading shared libraries: libbiomdi.so: cannot open shared object file: No such file or directory
Do you know what could I be doing wrong? Is there any directory that I should be in or any commands that I should run before the export?

**Comment by vfbsilva** [comment]
Same here:
`./NFIQ2: error while loading shared libraries: libnfiq2.so: cannot open shared object file: Error 40`
