### ISSUE TITLE
CMake 3 Requirement

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#10]
[New CMake build](https://github.com/usnistgov/NFIQ2/blob/ba0b03493bfcbc0b35c69aff0bfe5a704e9befc0/CMakeLists.txt#L1) requires version 3.3. NIST requires for NFIQ2 to run under CentOS, which does not ship by default with CMake 3. EPEL does [package CMake](https://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/c/cmake3-3.6.1-3.el6.x86_64.rpm) for the latest version of CentOS. It may be acceptable to allow this if we can eliminate older versions of CentOS. If so, instructions/scripts should detect and/or provide proper guidance. Specifically, the CMake 3.x binary is `cmake3` under CentOS. `cmake` is CMake 2.x.

**Comment by RLessmann** [comment]
cmake is called thru the shell scripts, so you better adapt the shell script to detect the cmake3 version

**Comment by gfiumara** [comment]
Per #30, CMake 3.14 is now required for at least the Android build. We may need to branch around this. I don't know how prudent it is to require folks to build and install a newer version of a package that is already bundled with the OS.

**Comment by gfiumara** [comment]
d462d50553977fae90b1bac590e0072d7d84dd91 checks for `cmake` vs `cmake3` and makes it easier to customize the path to CMake executable in the event it is installed at a non-standard path.

**Comment by ashwinrayaprolu1984** [comment]
I'm trying to run this on RaspberryPI
Older version of NFIQ2 ran successfully. I'm facing problems with latest version
git clone --single-branch --branch iso_wg3  https://github.com/usnistgov/NFIQ2.git
When i run 
./runCMake.sh 
I get this.
Missing target (x64, x32, android-arm32, android-arm64, android-x86, android-x64, ios-arm32, ios-arm64)

I'm new to CMAKE, Can someone let me know what all flags need to be changed in that Shell Script for the build to be successful on rasberry  ( ARMHF)
