### ISSUE TITLE
Compilation branching on OpenCV Major Versions

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#11]
Use of `CV_MAJOR_VERSION` is sprinkled throughout NFIQ2 code now. Since OpenCV 4 exists, we need to account for it. For API that we are using, CV 3 and 4 appear to be syntactically compatible, but as-is, using OpenCV 4 falls back to incompatible OpenCV 2 code, which fails to compile. We should alert/fail when using an unsupported version of OpenCV and be consistent with use of `CV_MAJOR_VERSION` throughout.

**Comment by RLessmann** [comment]
The current sources were only tested with OpenCV 2 and 3. I agree that we should address future versions, bujt we clearly name this also in the readme as below

The tested and approved OpenCV version is 2.4.13.6. The source were also experimentally compiled with the OpenCV version 3.4.5.
the open CV version can be changed within the top level Cmake file (see: set( OPENCV_VERSION "2.4.13.6")).

**Comment by gfiumara** [comment]
Added in 8fea809c8c9beb9969713850d3fbc8e6faf5a0f4.
