### ISSUE TITLE
isnan redefinitions

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#12]
`std::isnan` is part of the C++ standard, but we are redefining it in many source files, often differently in each. Eliminate all redefinitions and stick with the standards-based approach.

**Comment by RLessmann** [comment]
Some of the sources, espeacially the 3rd party pull in redefining isnan. this problem is inherit from the original NFIQ2 code. I agree that this is better to be solved, but it involves other parties as well.

**Comment by gfiumara** [comment]
Closed via 4a19c34611a92647d7654e7287e9a4439284b6ec.
