### ISSUE TITLE
computeQualityScore returned an error code,0,1

### ISSUE THREAD

**Issue by adraper2** [usnistgov/NFIQ2#136]
I am attempting to run NFIQ2 on contactless smartphone pngs. I am encountering problems though. The images are being re-sampled to 500 PPI but still fail to return a quality score. I know that I have built the package properly because the contact-based desktop scanner bitmaps work properly. I have attempted two versions of contactless images, one where our contactless images have corrected inter-ridge distance (to roughly 8 pixels) and one with no inter-ridge correction.

What I run:
./nfiq2 -i /media/example_contactless.png -m /media/NFIQ2/NFIQ2/nist_plain_tir-ink.txt -F -d

My debug message:
DEBUG 	| Model Initialization: 674.309 ms
DEBUG 	| Value of verbose flag: 0
DEBUG 	| Value of debug flag: 1
DEBUG 	| Value of speed flag: 0
DEBUG 	| Value of force flag: 1
DEBUG 	| Value of model flag: /media/NFIQ2/NFIQ2/nist_plain_tir-ink.txt
DEBUG 	| Value of recursive flag: 0
DEBUG 	| Processing Singles and AN2K files:
DEBUG 	| Processing Singles: 
DEBUG 	| Trying to obtain data from path: /media/example_contactless.png
DEBUG 	| Obtained data from path: /media/example_contactless.png
DEBUG 	| Obtaining FileType from data: /media/example_contactless.png
DEBUG 	| FileType Standard: /media/example_contactless.png
DEBUG 	| Successfully parsed image from data-blob: /media/example_contactless.png
DEBUG 	| Successfully passed bit and color depth check. Quantized?: 0
DEBUG 	| Successfully passed 500 PPI check. Re-sampled?: 1
/media/example_contactless.png,0,255,NFIQ2 computeQualityScore returned an error code,0,1
DEBUG 	| Processing Directories:
DEBUG 	| Processing Batch-files:
DEBUG 	| Processing RecordStores:

Any help debugging this would be greatly appreciated. I am unfamiliar with how this package works.

**Comment by gfiumara** [comment]
NFIQ requires 500 PPI images. We print a warning to the user about images not being 500 PPI when we cannot read the resolution header of the image format (for PNG, the `pHYs` header). We have a placeholder to integrate [NFIR](https://github.com/usnistgov/nfir) to resample the image, but this has not been included yet. Standby for that (Issue #137).

When you use the `-F` flag, you bypass this warning and placeholder in the command line interface, and then one feature or another within the NFIQ2 algorithm rejects the image for not being 500 PPI. If you are certain your image is 500 PPI, write the correct `pHYs` header to the PNG, with a utility like ImageMagick (e.g., `convert input.png -density 500 -units PixelsPerInch output.png`). You can also use ImageMagick to check the current value of the header (`identify -format "%x %U\n" input.png`)

Without `-F` but with `-d`, you'd see something like:

```
This Image is not 500 PPI. Would you like to re-sample this image to 500 PPI? (y/[N]): y
DEBUG 	| User approved the re-sample
/media/example_contactless.png,0,255,'Error: Resampling not implemented',0,1
```

Please also be advised that the random forest parameters shipping with NFIQ 2 are not tested with contactless images.
