### ISSUE TITLE
Disable FFMPEG in OpenCV 2 Configuration

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#14]
The OpenCV 2 codebase uses an older version of the FFMPEG API when enabled and FFMPEG is installed. The codebase does not branch on FFMPEG API versions. We do not need the features from FFMPEG, so we should explicitly disable FFMPEG to avoid the errors. Add `-DWITH_FFMPEG=OFF` to CMake run.

**Comment by RLessmann** [comment]
We better do this in the dedicated CmakeLists.txt file, which is located in the opncv folder.
