### ISSUE TITLE
Remove HISTOGRAM_FEATURES conditional

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#144]
NFIQ2 always reports feature histograms, so the conditional `HISTOGRAM_FEATURES` is not needed. It's defined at the beginning of each source file that uses it. The pre-processor should be removed.

At the same time, some calculations that happened before `HISTOGRAM_FEATURES` was always `1` are still calculated unnecessarily and exposed by enabling unused variable warnings (see #134). These variables can be removed.

**Comment by afiglarz** [comment]
Can be closed with merge of #157

**Comment by gfiumara** [comment]
Closed via #157.
