### ISSUE TITLE
Not existing directory.

### ISSUE THREAD

**Issue by Zakariae-drabech** [usnistgov/NFIQ2#151]
giving me this error when I do: cmake ..

**CMake Error at CMakeLists.txt:36 (add_subdirectory):
  add_subdirectory given source
  "/home/zakariae/NFIQ2-master/fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/"
  which is not an existing directory.**
Even I add this directory, giving more errors like this

**Comment by gfiumara** [comment]
You did not clone the subdirectories. Checkout the repo with `git clone --recursive` or `git submodule update --init --recursive` for the first time to update them after the initial clone.
