### ISSUE TITLE
 NMake Makefiles does not support platform specification, but platform x64 was specified.

### ISSUE THREAD

**Issue by Zakariae-drabech** [usnistgov/NFIQ2#155]
When I tried to install NFIQ2, show me this error
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:3 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by gfiumara** [comment]
1. You're probably not running in a Visual Studio Native Tools Command Prompt so your PATHs are not set up correctly.
 2. We have not tested with the "NMake Makefiles" generator for CMake, only MSVC on Windows, so it might not work.

I've noticed you're submitting compilation troubleshooting requests. We have[ pre-built binaries of the pre-release of NFIQ 2.1 available](https://github.com/usnistgov/NFIQ2/releases). I would suggest using that if you are not going to actively be working on improvements to NFIQ 2. If you are going to be working on issues, please reach out!
