### ISSUE TITLE
Hardcoded OpenCV lib on Windows

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#18]
[This line](https://github.com/usnistgov/NFIQ2/blob/ba0b03493bfcbc0b35c69aff0bfe5a704e9befc0/NFIQ2/NFIQ2Algorithm/CMakeLists.txt#L90) seems to imply a hardcoded OpenCV version. Is it necessary?

**Comment by RLessmann** [comment]
Open CV on windows carry the version within the name of the static libs. Due the lowest version we support is 2.4.13.6, we can use this directly in the cmake configuration. BTW as you see in the out section we differentiate between Open CV  2 and 3 here.

**Comment by gfiumara** [comment]
All of these conditionals and manually specifying include/lib paths can likely be avoided by using the generated CMake files that end up in the build (CMakeFiles/Export/share/*.cmake). This also likely solves #16 and #15 by correctly including required OpenCV dependencies. If we're switching to CMake, let's take advantage of the benefits provided by CMake.

**Comment by gfiumara** [comment]
Need to confirm on Windows and other versions of OpenCV besides 2, but should be using the generated `OpenCVConfig.cmake` file as of 836dbdbc870623bcf8915b4b8e3f87657af4e055.

**Comment by gfiumara** [comment]
Confirmed as working under Windows.
