### ISSUE TITLE
Passing arguments to build

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#19]
It is common to want to pass more arguments to the build/configure step, especially a prefix as to where to install the resulting libraries and binaries.

**Comment by RLessmann** [comment]
Please explain further, installation and deployment wasn't the major target of the change. Our main objective was to be able to build the code on all platforms within the same file tree and not interfere with each other.

**Comment by gfiumara** [comment]
Closing, as CMake should provide this.
