### ISSUE TITLE
Run the binary.

### ISSUE THREAD

**Issue by benitofe** [usnistgov/NFIQ2#2]
Hello, I already installed the application, but how can I run it? Which binary?

"Library Path for libbiomdi will need to be set to run the binary."

**Comment by bmwoodgate** [comment]
If you installed NFIQ2 you will call the NFIQ2 binary installed in /usr/local/bin.
And you will need add /usr/local/lib to your LD_LIBRARY_PATH or DYLD_LIBRARY_PATH, depending if you are running on linux or mac.
