### ISSUE TITLE
Case-insensitive arguments

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#20]
SINGLE/BATCH and WSQ/BMP are case-sensitive. Make them case insensitive. Better yet, support `getopt` style arguments to avoid position dependence and extra typing.

**Comment by RLessmann** [comment]
This problem is inherited from the original WSQ sources and wasn't addressed in this scope.

**Comment by gfiumara** [comment]
Agreed, this is a general comment to be fixed at some point in the future.

**Comment by gfiumara** [comment]
Resolved in 76c1dba8d69ad928b71c8ed35b3fd74945cf5ef2.
