### ISSUE TITLE
Wikis wide open

### ISSUE THREAD

**Issue by madclumsil33t** [usnistgov/NFIQ2#237]
Anyone who is signed in can create and modify wiki pages on certain repos like https://github.com/usnistgov/fipy/wiki. This is sometimes the intended behavior, but locking down so it requires approval is preferred. Thanks!

**Comment by gfiumara** [comment]
Hi @madclumsil33t, the wiki on this repo should be locked down to only those with push access. Are you seeing something different (i.e., can you edit the wiki on this repository)? Are you asking for me to forward this request to someone else at NIST? Thanks!

<img width="413" alt="Screen Shot 2021-04-22 at 4 01 45 PM" src="https://user-images.githubusercontent.com/419642/115778149-35e2d200-a384-11eb-8e22-ed740a7493f9.png">

**Comment by gfiumara** [comment]
Tagging @guyer of https://github.com/usnistgov/fipy for visibility if it's something to fix there, but this does not effect this repo. Closing.

**Comment by guyer** [comment]
Thanks for forwarding to me. I've restricted FIPy's wiki to push access, now, too.
