### ISSUE TITLE
latest Windows-Release fails to pass compliance test

### ISSUE THREAD

**Issue by JoMe2704** [usnistgov/NFIQ2#269]
I have download and tested the latest Windows binary (nfiq2-2.0.999.900-win64.msi). The NFIQ2 scores computed by that release for the compliance test set don't match the expected values. There are just slight deviations in the individual features, but the quality scores differ by up to 18 (for FVC2000_Db1_91_1.bmp). Please find the computed values attached. 
[Output_2.0.999.900-win64_compliance_test_set.csv.zip](https://github.com/usnistgov/NFIQ2/files/6466031/Output_2.0.999.900-win64_compliance_test_set.csv.zip)

Since this binary has been published as release version 2.1-pre, I wonder if compliance to NFIQ2 is intended?

**Comment by gfiumara** [comment]
HI @JoMe2704, there's been some code changes/bug fixes in the repo here that have affected some scores, so the version of the scores hosted here _now_ are slightly different than when 2.1-pre was posted. We should post a new version soon. I believe you should be able to get identical results if you used an older version of the scores (_maybe_ [this version](https://github.com/usnistgov/NFIQ2/blob/ce71feff546a387a0777136b259f19d217255535/complianceTestSet/CTS_MASTER_OUTPUT.csv)).

**Comment by JoMe2704** [comment]
Did the CTS data set change since NFIQ2 was issued? I have a version with images from FVC2000 DB1&3 and FCVC2002 DB1 as outlined in Section A.2 of the (final) draft NFIQ2 report. There, FVC2000/Db1/91_1 should give a score of 32, but the 2.1-pre release gives 14. 

For the new test set (which I have just obtained) the scores computed with  the 2.1-pre release are as listed in the CTS_MASTER_OUTPUT.csv you referred to.

**Comment by gfiumara** [comment]
Correct, the CTS has changed and no longer includes any FVC images. Please see the [updated README](https://github.com/usnistgov/NFIQ2/blob/master/complianceTestSet/README.md).

**Comment by JoMe2704** [comment]
But still, any NFIQ2 release should reproduce the scores listed in the draft report for the FVC images, right?

**Comment by gfiumara** [comment]
No. There have been numerous bug fixes in the core algorithm between the initial NFIQ 2 release and 2.1. Scores between 2 and 2.1 final (to be released) _will_ be different. Scores on and after 2.1 should be stable and consistent on all platforms.

**Comment by JoMe2704** [comment]
So 2.1 is functionally different from 2.0?  This answers my question. However, may I suggest to document that fact in the repository.

**Comment by gfiumara** [comment]
Noted. I have updated our [Frequently Asked Questions](https://github.com/usnistgov/NFIQ2/wiki/Frequently-Asked-Questions) page and will close this issue. Thanks!

Please register for our upcoming workshop if you haven't already: https://eab.org/events/program/248
