### ISSUE TITLE
BMP Input Metadata

### ISSUE THREAD

**Issue by Portagoras** [usnistgov/NFIQ2#29]
I got problems with the my input files, as I use them from different sources for comparison.
Some do work, others don't and give me an error, like that the picture has to be "GreyScale" (it's gray btw.), even if the image type is set.

Do you have a reliable imagemagic convert query/parameter set to convert pictures into a fitting format?

Thanks for your help.

**Comment by gfiumara** [comment]
The BMP parser in NFIQ2 right now is admittedly not very robust. It does not support some rudimentary BMP techniques like RLE, etc. I hope to have this updated in the future. In the mean time, I would suggest adding `-compress None` to your `convert` argument string to create what is essentially a raw image with a BMP header. The NFIQ2 binary as it is now should be able to handle this.

**Comment by Portagoras** [comment]
Thanks for the quick feedback, but I did use the compress function. For other images it helped to set interlace to plane for some reason. It would be enough if this get's updated in the future, as I found a way to do what I want, it just takes ages, as I got around 1.1 GiB of Fingerprint images to convert for research.

Thanks for you help tho!

**Comment by gfiumara** [comment]
You might also try explicitly setting an older version of the BMP standard. Off the top of my head, I think that may have been assumed in the rudimentary parser as well. Something like:

`convert image.png -colorspace Gray -compress None -depth 8 BMP3:image.bmp`

**Comment by iColdplay** [comment]
emmmmm
when I use my fingeprint image .bmp files, use command "./NFIQ2 SINGLE finger.bmp BMP out1 out2" and I always get the same error.
NFIQ2: Compute quality score for fingerprint image finger.bmp
ERROR => Return code [36]: Wrong file type: wrong info header detected (e.g. compression, planes, size)
what should I do?

**Comment by gfiumara** [comment]
@iColdplay: The latest version of the command line interface supports all kinds of BMPs and all other image formats. See the iso_wg3 branch for the latest code.

Alternatively, please try the suggestion from this issue and in the [FAQ](https://github.com/usnistgov/NFIQ2/wiki/Frequently-Asked-Questions):
`convert INPUT.BMP -depth 8 -compress None -colorspace Gray -colors 256 BMP3:OUTPUT.bmp` You may need to remove `-colors 256` depenging on your version of ImageMagick.
