### ISSUE TITLE
Build-time downloads should be submodules

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#32]
It may be wise to use git submodules instead of relying on GitHub-generated zip files of repository code for OpenCV and BioMDI. Otherwise, documentation should be improved on how exactly to use pre-downloaded code. See also #24.

**Comment by gfiumara** [comment]
78c82b8021295a3c726396718958acc70425845b replaces this for BioMDI.

**Comment by gfiumara** [comment]
Everything except OpenCV is now a submodule. However, per #50, we should be making these external projects too.

**Comment by Tilahun-Addis** [comment]
When run the NFIQ2.cpp this error comes collect2: error: ld returned 1 exit status. What is the problem do you help me?

**Comment by gfiumara** [comment]
Resolved for last project, OpenCV, in #102.
