### ISSUE TITLE
Can NFIQ2 compare iso files?

### ISSUE THREAD

**Issue by xellDart** [usnistgov/NFIQ2#338]
I use NFIQ library to calculate NFIQ2 Score and generate iso files using   

err = fjfx_create_fmd_from_raw(image, 500, height, width, FJFX_FMD_ISO_19794_2_2005, tmpl, &size);...

Can I compare two iso files (two different fingerprints) using this library?

Thanks

**Comment by gfiumara** [comment]
This is not an NFIQ 2 API method. The NFIQ 2 API only supports generating quality from decompressed grayscale 8-bit 500 PPI images and does not decode any image codecs. The NFIQ 2 CLI _does_ support this type of parsing, so look at that code for more assistance.
