### ISSUE TITLE
NFIQ2 for minutiae cropped patches

### ISSUE THREAD

**Issue by gowrijsuria** [usnistgov/NFIQ2#349]
Hi, 
I tried to run Nfiq2 for minutiae cropped patches. However, they don't seem to work, it gives the following error: 

Error: NFIQ2 computeQualityScore returned an error code: Cannot compute Frequency Domain Analysis (FDA): Not enough data to generate histogram bins (is the image blank?)

Could you please confirm if nfiq2 will work for patches or provide a solution for the same?

**Comment by gfiumara** [comment]
NFIQ 2 is designed to compute a quality score for finger images at 500 ppi spatial sampling rate and a bit depth of 8 bit for the grayscale pixel intensity values scanned or captured using optical area sensors.
