### ISSUE TITLE
NFIQ2::FingerprintImageData from bmp or wsq

### ISSUE THREAD

**Issue by letisoft** [usnistgov/NFIQ2#352]
Hello,

How can I get FingerprintImageData from bmp or wsq?

Any sample will help.

Thanks!

**Comment by gfiumara** [comment]
The NFIQ2 CLI makes use of Biometric Evaluation framework for this. Code is included in this repo.

**Comment by letisoft** [comment]
Hello,

Can you please point me to any src to check?

Thanks in advance!
V

**Comment by gfiumara** [comment]
NFIQ2/NFIQ2Algorithm/src/tool/nfiq2_ui_image.cpp

**Comment by letisoft** [comment]
Thank you very much!

sorry I had a look, but still cannot get it how to use bmp to get FingerprintImageData.
I have the raw data from the sensor, I can get it in bmp. I know the image dimensions (W x H and DPI) but not sure what's next!

In short I have android device with a cross match sensor and I want to make sure images are good enough!

I do really appreciate you help & patience with non experts!

V

**Comment by gfiumara** [comment]
On Android, if you have a BMP, seems like you can use [`getPixels`](https://developer.android.com/reference/android/graphics/Bitmap#getPixels(int[],%20int,%20int,%20int,%20int,%20int,%20int)) to decompress it into raw bytes. Then pass the buffer to this [FingerprintImageData constructor](https://github.com/usnistgov/NFIQ2/blob/29595e20c6d372c772f9d9a07d0ecd9d6a6e5c34/NFIQ2/NFIQ2Algorithm/include/nfiq2_fingerprintimagedata.hpp#L46). You're going to need to convert the `int[]` to `uint8_t[]` (i.e., `unsigned char`) though. Sorry, I can't be much further help there.
