### ISSUE TITLE
Could NOT find BERKELEYDB

### ISSUE THREAD

**Issue by sodmlx2** [usnistgov/NFIQ2#357]
I'm trying to compile nfiq2 project. but I'm having trouble to loading the environment variables

Could NOT find BERKELEYDB (missing: BERKELEYDB_LIBRARY BERKELEYDB_INCLUDE_DIR)

I set the variables in CMakeGUI:
* BERKELEYDB=C:/vcpkg/packages/berkeleydb_x64-windows
* BERKELEYDB_LIBRARY=C:/vcpkg/packages/berkeleydb_x64-windows/include
* BERKELEYDB_INCLUDE_DIR=C:/vcpkg/packages/berkeleydb_x64-windows/lib

**Comment by gfiumara** [comment]
Please see [Build Notes](https://github.com/usnistgov/NFIQ2#build-notes) in the README. If you had to manually specify BerkeleyDB variables to CMake, I'd guess you did not pass the vcpkg CMake toolchain file to CMake. You may also be building NFIQ 2 for an architecture for which you do not have the vcpkg dependencies (Win32 vs x64).

**Comment by sodmlx2** [comment]
solved installing libbiomeval dependencies ;)

vcpkg install openssl openjpeg libjpeg-turbo libpng tiff zlib msmpi berkeleydb sqlite3 zlib hwloc ffmpeg

thx! @gfiumara
