### ISSUE TITLE
Nfiq2Api.lib equivalent on LINUX?

### ISSUE THREAD

**Issue by indianscorpion** [usnistgov/NFIQ2#369]
I couldn't find the Nfiq2Api.lib equivalent on LINUX
in your package. nfiq2-2.2.0-1.el7.x86_64.rpm or nfiq2-2.2.0-1.el8.x86_64.rpm.

does it exist? if not, how to make one?

**Comment by gfiumara** [comment]
It's in `-devel`. That said, it's not supported (on Linux or Windows) and [will be removed ASAP](https://github.com/usnistgov/NFIQ2/blob/2a899239d3d72f302cad859145745e8703e32ab0/NFIQ2/NFIQ2Api/CMakeLists.txt#L54), so please don't use it.

**Comment by indianscorpion** [comment]
if not using it, should I develop a own one on LINUX?
what do you recommend?
