### ISSUE TITLE
Failed to install the LINUX package, where to find the dependencies?

### ISSUE THREAD

**Issue by indianscorpion** [usnistgov/NFIQ2#370]
-bash-4.2$ rpm -i nfiq2-2.2.0-1.el7.x86_64.rpm
error: Failed dependencies:
        libdb-cxx is needed by nfiq2-2.2.0-1.x86_64
        libdb_cxx-5.3.so()(64bit) is needed by nfiq2-2.2.0-1.x86_64
        libopenjp2.so.7()(64bit) is needed by nfiq2-2.2.0-1.x86_64
        openjpeg2 is needed by nfiq2-2.2.0-1.x86_64
        xz-lzma-compat is needed by nfiq2-2.2.0-1.x86_64
-bash-4.2$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Comment by indianscorpion** [comment]
I was able to install the following packages from pkgs.org to make the binary nfiq2 work.
libdb-cxx-5.3.21-25.el7.x86_64.rpm
libdb-5.3.21-25.el7.x86_64.rpm
openjpeg2-2.3.1-3.el7_7.x86_64.rpm
xz-lzma-compat-5.2.2-1.el7.x86_64.rpm
xz-5.2.2-1.el7.x86_64.rpm
xz-libs-5.2.2-1.el7.x86_64.rpm

**Comment by indianscorpion** [comment]
Now, why the so file wasn't provided? how can we integrate the NFIQ2 library with a LINUX C program?

**Comment by gfiumara** [comment]
Development libraries are provided in the -devel package.
