### ISSUE TITLE
Missing LINUX library files in the installation package.

### ISSUE THREAD

**Issue by indianscorpion** [usnistgov/NFIQ2#371]
Missing LINUX library files in the installation package.
Only nfiq2 binary was distributed.

**Comment by indianscorpion** [comment]
trying to build the source code on LINUX now...

**Comment by indianscorpion** [comment]
got build error below:
[ 17%] Completed 'OpenCV'
[ 17%] Built target OpenCV
[ 19%] Building CXX object fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/CMakeFiles/FRFXLL.dir/lib/FRFXLLCreateContext.cpp.o
[ 21%] Building CXX object fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/CMakeFiles/FRFXLL.dir/lib/FRFXLLCreateFeatureSet.cpp.o
[ 23%] Building CXX object fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/CMakeFiles/FRFXLL.dir/lib/FRFXLLCreateFeatureSetFromRaw.cpp.o
[ 26%] Building CXX object fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/CMakeFiles/FRFXLL.dir/lib/FRFXLLCreateFeatureSetInPlace.cpp.o
[ 28%] Building CXX object fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/CMakeFiles/FRFXLL.dir/lib/FRFXLLCreateFeatureSetInPlaceFromRaw.cpp.o
[ 30%] Building CXX object fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/CMakeFiles/FRFXLL.dir/lib/FRFXLLCreateLibraryContext.cpp.o
[ 32%] Building CXX object fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/CMakeFiles/FRFXLL.dir/lib/FRFXLLDuplicateHandle.cpp.o
[ 34%] Building CXX object fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/CMakeFiles/FRFXLL.dir/lib/FRFXLLExport.cpp.o
[ 36%] Building CXX object fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/CMakeFiles/FRFXLL.dir/lib/FRFXLLGetLibraryVersion.cpp.o
[ 39%] Building CXX object fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/CMakeFiles/FRFXLL.dir/lib/FRFXLLGetMinutiae.cpp.o
[ 41%] Linking CXX shared library libFRFXLL.so
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
gmake[2]: *** [fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/libFRFXLL.so] Error 1
gmake[1]: *** [fingerjetfxose/FingerJetFXOSE/libFRFXLL/src/CMakeFiles/FRFXLL.dir/all] Error 2

**Comment by gfiumara** [comment]
Please install the required system dependencies. GitHub issues are not the place for troubleshooting, but rather, for identifying and tracking issues with the code. Thank you.
