### ISSUE TITLE
License issue for commercial adoption. (FingerJetFX OSE (LGPLv3 license)

### ISSUE THREAD

**Issue by netx123** [usnistgov/NFIQ2#372]
As NFIQ2 has a dependency on FingerJetFX and this library is licensed under LGPLv3 license.

How can commercial software possibly adopt NFIQ2 when it ultimately falls under LGPLv3 license terms?

As any project using LGPLv3 license must ultimately become open source,, which for proprietary commercial projects this is not compatible.

**Comment by gfiumara** [comment]
I think you are confusing GPL and LGPL. LGPL libraries are allowed to be linked to other licensed code, including commercial. The remainder of NFIQ2 is public domain (e.g., no license).
