### ISSUE TITLE
Failed to link opencv using g++ on LINUX

### ISSUE THREAD

**Issue by indianscorpion** [usnistgov/NFIQ2#374]
Failed to link opencv using g++ on LINUX

Trying to link the library using g++ as below, it gave tons of errors. (cmake on examples works)
 -lnfiq2 -lFRFXLL_static -lopencv_core -lopencv_imgproc -lopencv_ml

errors:
undefined reference to `cv::softdouble::operator*(cv::softdouble const&) const'

**Comment by gfiumara** [comment]
If the CMake in the example works, then the issue would be in your code, no? You are likely not linking all the OpenCV libraries you need for your project.

**Comment by indianscorpion** [comment]
I linked all the libraries in your release package as below, which one am I missing?
-lnfiq2 -lFRFXLL_static -lopencv_core -lopencv_imgproc -lopencv_ml
your lib64:
libFRFXLL_static.a
libnfiq2.a
libnfir.a
libopencv_imgproc.a
libopencv_ml.a
libopencv_core.a
libNfiq2Api.so
libFRFXLL.so

**Comment by indianscorpion** [comment]
it is using CV_EXPORTS softdouble cos( const softdouble& a );
should I include any link options?

**Comment by gfiumara** [comment]
It's in opencv_core. You are likely not linking in an appropriate order. This is not an NFIQ 2 issue.

```
$ nm -C libopencv_core.a | grep 'T cv::softdouble::operator\*'
0000000000000000 T cv::softdouble::operator*(cv::softdouble const&) const
```

**Comment by indianscorpion** [comment]
yes, the correct linking order is as below:
-lnfiq2 -lFRFXLL_static -lopencv_ml -lopencv_imgproc -lopencv_core
