### ISSUE TITLE
Windows and LINUX, same image got different NFIQ2 score, why?

### ISSUE THREAD

**Issue by indianscorpion** [usnistgov/NFIQ2#375]
Windows and LINUX, same image got different NFIQ2 score, why?
Both are 64-bit.
![image](https://github.com/usnistgov/NFIQ2/assets/18605146/3a2230d8-42fa-42a2-ad45-24df77713817)

**Comment by gfiumara** [comment]
Almost certainly, you are using your own copy of OpenCV that you build, which likely does not turn off all the optimizations and liberties OpenCV takes. We test NFIQ 2 on millions of images on all supported platforms and show no differences.

**Comment by indianscorpion** [comment]
I am using your 64-bit release libraries.
On windows, I used Nfiq2Api.dll. and on LINUX I used -lnfiq2 -lFRFXLL_static -lopencv_ml -lopencv_imgproc -lopencv_core
Does this matter?

**Comment by gfiumara** [comment]
You are **not**, because as we established in #367 (now an issue in #368), we accidentally didn't include OpenCV libraries. We need to fix this.
