### ISSUE TITLE
Error while building NFIQ2 in ndk-build

### ISSUE THREAD

**Issue by TusDoss** [usnistgov/NFIQ2#4]
jni/opencv2/core/mat.hpp:367: error: undefined reference to 'cv::Mat::deallocate()'
jni/opencv2/core/mat.hpp:298: error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
jni/opencv2/core/mat.hpp:367: error: undefined reference to 'cv::Mat::deallocate()'
jni/opencv2/core/mat.hpp:278: error: undefined reference to 'cv::fastFree(void*)'
jni/opencv2/core/mat.hpp:278: error: undefined reference to 'cv::fastFree(void*)'
jni/opencv2/core/mat.hpp:353: error: undefined reference to 'cv::Mat::create(int, int const*, int)'
jni/opencv2/core/mat.hpp:353: error: undefined reference to 'cv::Mat::create(int, int const*, int)'
jni/opencv2/core/mat.hpp:298: error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
jni/opencv2/core/mat.hpp:367: error: undefined reference to 'cv::Mat::deallocate()'
jni/opencv2/core/mat.hpp:278: error: undefined reference to 'cv::fastFree(void*)'
jni/opencv2/core/mat.hpp:298: error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
jni/opencv2/core/mat.hpp:278: error: undefined reference to 'cv::fastFree(void*)'
jni/opencv2/core/mat.hpp:367: error: undefined reference to 'cv::Mat::deallocate()'
jni/opencv2/core/mat.hpp:298: error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
jni/opencv2/core/operations.hpp:2592: error: undefined reference to 'cv::fastMalloc(unsigned int)'
jni/src/flann/miniflann.cpp:317: error: undefined reference to 'cv::Exception::Exception(int, std::string const&, std::string const&, std::string const&, int)'
jni/src/flann/miniflann.cpp:317: error: undefined reference to 'cv::error(cv::Exception const&)'
jni/src/flann/miniflann.cpp:317: error: undefined reference to 'cv::Exception::~Exception()'
jni/src/flann/miniflann.cpp:315: error: undefined reference to 'cv::format(char const*, ...)'
jni/src/flann/miniflann.cpp:315: error: undefined reference to 'cv::Exception::Exception(int, std::string const&, std::string const&, std::string const&, int)'
jni/src/flann/miniflann.cpp:315: error: undefined reference to 'cv::error(cv::Exception const&)'
jni/src/flann/miniflann.cpp:315: error: undefined reference to 'cv::Exception::~Exception()'
jni/src/flann/miniflann.cpp:317: error: undefined reference to 'cv::Exception::~Exception()'
jni/opencv2/flann/lsh_table.h:276: error: undefined reference to 'cv::Exception::Exception(int, std::string const&, std::string const&, std::string const&, int)'
jni/opencv2/flann/lsh_table.h:276: error: undefined reference to 'cv::error(cv::Exception const&)'
jni/opencv2/flann/lsh_table.h:276: error: undefined reference to 'cv::Exception::~Exception()'
jni/src/flann/miniflann.cpp:315: error: undefined reference to 'cv::format(char const*, ...)'
jni/src/flann/miniflann.cpp:315: error: undefined reference to 'cv::Exception::Exception(int, std::string const&, std::string const&, std::string const&, int)'
jni/src/flann/miniflann.cpp:315: error: undefined reference to 'cv::error(cv::Exception const&)'
jni/opencv2/core/operations.hpp:2592: error: undefined reference to 'cv::fastMalloc(unsigned int)'
jni/src/flann/miniflann.cpp:315: error: undefined reference to 'cv::format(char const*, ...)'
jni/opencv2/core/operations.hpp:2592: error: undefined reference to 'cv::fastMalloc(unsigned int)'
jni/src/flann/miniflann.cpp:680: error: undefined reference to 'cv::format(char const*, ...)'
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi-v7a/liboasys.so] Error 1

Any help...

**Comment by bmwoodgate** [comment]
Are you trying to build NFIQ2 on android?

**Comment by TusDoss** [comment]
Most errors are occurred in the OpenCV modules

**Comment by bmwoodgate** [comment]
Android is not officially supported, but looks like you're not able to link against opencv correctly.
