### ISSUE TITLE
Raster Images Only

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#41]
It is suggested that the NFIQ 2 library only accept raster image data, instead of specifying image formats. Clients (including an official NFIQ 2 binary) will be required to do any necessary image decompression before passing to an NFIQ 2 routine for quality calculation.

**Comment by Tilahun-Addis** [comment]
could you tell me how to run NFIQ2 on  ubuntu 14.04

**Comment by gfiumara** [comment]
Closing manually, since this has been handled by #87 (GitHub waits until PRs are merged into branch `master`, but we are using branch `iso_wg3`).
