### ISSUE TITLE
Documentation to compile on numerous systems...

### ISSUE THREAD

**Issue by rruffer** [usnistgov/NFIQ2#47]
Dear, Nbis 5.0.0 has rich documentation for compiling your code into various operating systems. In the case of Nfiq 2.0 it is difficult to know what to do. At the moment I want to compile for windows and I don't know exactly what to do. Could you create a file containing the walkthrough to compile Nfiq 2.0? How do the INSTALL_CYGWIN.txt, INSTALL_LINUX_MACOSX.txt, INSTALL_WINDOWS.txt files in nbis 5.0.0?

**Comment by gfiumara** [comment]
The `master` branch of NFIQ 2 only explicitly supports  Linux at this point, though it should build on other systems. This is being corrected as we speak in the `iso_wg3` branch and will have official support and documentation. Thanks for your patience.

**Comment by rruffer** [comment]
thanks

**Comment by rruffer** [comment]
Any evolution in the documentation of this component?

**Comment by gfiumara** [comment]
Per previous comment, `iso_wg3` branch builds cleanly on Windows. Will likely be merged into `master` by January 2021 + pre-built binary.
