### ISSUE TITLE
 libbiomdi 

### ISSUE THREAD

**Issue by mahasalrasheed** [usnistgov/NFIQ2#48]
can you explain what "Library Path for libbiomdi will need to be set to run the binary." means in detail and what should i change ?

**Comment by gfiumara** [comment]
If you don't install the libraries into a directory known by `ldconfig` then you'll need to set `LD_LIBRARY_PATH` (`DYLD_LIBRARY_PATH` on macOS) to include the path to `libbiomdi.so`. For example:

```
export LD_LIBRARY_PATH=/home/gfiumara/NFIQ2-master/biomdi/common/lib
```

This won't be necessary in the next version of NFIQ 2.
