### ISSUE TITLE
libnfiq2.so

### ISSUE THREAD

**Issue by johnnyy** [usnistgov/NFIQ2#5]
This error occurs: "NFIQ2: error while loading shared libraries: libnfiq2.so: can not open shared object file: No such file or directory", but I already installed everything that was necessary to use the NFIQ2.
In the libNFIQ2 folder you can find this missing file. What could have happened?

**Comment by johnnyy** [comment]
After passing the path of the required files, you must use the command "ldconfig".

**Comment by ogbanugot** [comment]
@johnnyy I know this has been closed but can you show how you resolved this. Can't seem to figure this one out. Thanks.

**Comment by ogbanugot** [comment]
Never mind, we need to run 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/NFIQ2/biomdi/common/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/NFIQ2/biomdi/fingerminutia/src/libfmr/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/NFIQ2/libOpenCV/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/NFIQ2/NFIQ2/NFIQ2Algorithm/lib/
then run "ldconfig"
Wonder why this is not in the reamme?

**Comment by gfiumara** [comment]
Setting `LD_LIBRARY_PATH` should not require running `ldconfig`. That should only be necessary when adding paths to `/etc/ld.so.conf`. 

You may also choose to modify the build system to set a hardcoded `RPATH` to avoid either of these steps.

We will update the documentation for the shared library build in an upcoming release.

**Comment by ogbanugot** [comment]
Thanks a lot @gfiumara . Also, just a follow up, is this the correct way to run the program in single mode?
NFIQ2 SINGLE /home/pathtoimage/1.bmp BMP true
This just brings up the help message again.

**Comment by gfiumara** [comment]
> NFIQ2 SINGLE /home/pathtoimage/1.bmp BMP true

@ogbanugot you need another boolean (`true` or `false`) for if you want speed values printed.

**Comment by ogbanugot** [comment]
Thanks!
