### ISSUE TITLE
Building process with Mac is incomplete.

### ISSUE THREAD

**Issue by learning000** [usnistgov/NFIQ2#53]
Iam trying to build master branch with mac os but not working.

I have done git clone, later i run  below one 
mkdir libOpenCV && cd libOpenCV && cmake -D CMAKE_MAKE_PROGRAM=make ../OpenCV && make opencv_core opencv_ts opencv_imgproc opencv_highgui opencv_flann opencv_features2d opencv_calib3d opencv_ml opencv_video opencv_objdetect opencv_contrib opencv_nonfree opencv_gpu opencv_photo opencv_stitching opencv_videostab
 
later did 

make
but after that there is no documentation about rest of the building process to get .sln file.

**Comment by gfiumara** [comment]
No `.sln` (Visual Studio Solution) file would ever be generated under macOS. Additionally, on modern versions of macOS, you'll need to update the version of OpenCV 2.x to the latest in the series to restore the build.

We are actively developing in the `iso_wg3` branch, which will get around this problem, but that branch is **development only** and not ready for use yet. It can generate a `.sln` file under Windows.
