### ISSUE TITLE
Statically building an NFIQ2 executable

### ISSUE THREAD

**Issue by stadelmanma** [usnistgov/NFIQ2#7]
My team has a need for a statically built NFIQ2 executable and I was interested if there was an "supported" way of doing this? Compared to hacking away at the makefiles in a local copy/fork of the source code. 

If there isn't a supported way to do this already I'd be more than willing to push my changes back to you all when I manage to generate a static build.

Thanks,
Matt

**Comment by gfiumara** [comment]
Hi Matt @stadelmanma, apologies for the almost year-long delay. This is being implemented.
