### ISSUE TITLE
Problems with installing openCV

### ISSUE THREAD

**Issue by justjuust** [usnistgov/NFIQ2#79]
Hi!

I am a bit new at using cmake.
While following the install steps and installing OpenCV I ran into the following issue 

CMake Error at cmake/OpenCVPackaging.cmake:128 (if):
  if given arguments:

    "EQUAL" "5"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:1108 (include)

-- Configuring incomplete, errors occurred!
See also "/mnt/c/NFIQ2/libOpenCV/CMakeFiles/CMakeOutput.log".
See also "/mnt/c/NFIQ2/libOpenCV/CMakeFiles/CMakeError.log".

In CMakeError.log i found the following message:

/mnt/c/NFIQ2/libOpenCV/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: sys/videoio.h: No such file or directory
    1 | #include <sys/videoio.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [CMakeFiles/cmTC_aaff1.dir/build.make:66: CMakeFiles/cmTC_aaff1.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory '/mnt/c/NFIQ2/libOpenCV/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_aaff1/fast] Error 2

Any help is welcome.

best

**Comment by gfiumara** [comment]
Are you using the iso_wg3 branch or master? 
 * If master, try the iso_wg3 branch. This is where active development is happening.
 * If iso_wg3, please provide more information (OS, OpenCV version). Looks like you're using Cygwin based on the paths and that it's failing to find a header file dealing with video, which probably isn't necessary for NFIQ2.

**Comment by justjuust** [comment]
Hi,

Thank you for your help. I was using the wrong branch.

Best,
Just
