### ISSUE TITLE
Actionable quality no longer output

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#9]
[This change](https://github.com/usnistgov/NFIQ2/blob/ba0b03493bfcbc0b35c69aff0bfe5a704e9befc0/NFIQ2/NFIQ2Algorithm/src/NFIQ2.cpp#L364) removes actionable quality output. We should decide if this information should be output in BATCH mode. If no, the actionable quality headers need to be removed from the CSV.

**Comment by RLessmann** [comment]
Original the compliance test set was shipped with some *csv file with the expected values. These expected values did not contain the actionable feedback values and therefore where not easily comparable, thts why we temporary removed the actionable feedback output. Our mistake to not put it back in.
